In [1]:
import numpy as np
ary = np.array([1,2,3,5,8])
ary = ary + 1
print (ary[1])

3


In [5]:
a = np.empty(4, dtype = int)
print(a)

[-1381682750 -1945866053  1531299394  1721689979]


In [125]:
import numpy as np
a=np.arange(11)
for i in a:
    if i==5:
        print(1,end=" ")
    else:
        print(0) 

0
0
0
0
0
1 0
0
0
0
0


In [33]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [36]:
np.random.rand()

0.8255309989974581

In [313]:
np.random.randint(10)

2

In [319]:
import numpy as np

a=np.eye(5,6, dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [310]:
#Cut the Rope

import numpy as np
b =np.linspace(0 , 5 , num = 9, endpoint = False)
for i in b:
    if i != 0.0 and i != 5.0:
        print(round(i , 2))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


In [57]:
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
print (a[s])

[2 4 6]


In [307]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

arr1 = input_[2,:3]
for i in arr1:
    print(i, end = " ")

print()

arr2 = input_[1:4,3]
for i in arr2:
    print(i, end = " ")
    
print()

arr3 = input_[2:4,:]


for i in arr3:

    for j in i:
        print(j, end = " ")
    
print()

arr4 = input_[1:3,1:3]
for i in arr4:
    for j in i:
        print(j, end = " ")

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

In [306]:
#Non-Zero elements

import numpy as np
a=np.array([1,2,0,0,4,0])

b=np.where(a!=0)
for i in b[0]:
    print(i,end=" ")

0 1 4 

In [305]:
#Multiples of 3

import numpy as np
arr = np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
ind = np.where(arr % 3 == 0)
ans = ind[0]
for i in ans:
    print(i, end = " ")

1 4 7 

In [212]:
import numpy as np
a=np.linspace(1,11,10, dtype=int)

for i in a:
    if i%2==0 or i==10:
        print(i,end=" ")

    else:
        print(-1,end=" ")

-1 2 -1 4 -1 6 -1 8 -1 -1 

In [304]:
#Replace Max

import numpy as np
arr = [11, 2, 13, 4, 15, 6, 27, 8, 19]
arr = np.array(arr)
arr[arr.argmax()] = 0
for i in arr:
    print(i)

11
2
13
4
15
6
0
8
19


In [303]:
import numpy as np

a=np.linspace(1,10,10, dtype=int)

for i in a:
    if (i>=3) & (i<=8):
        print(-1)
    else:
        print(i)

1
2
-1
-1
-1
-1
-1
-1
9
10


In [302]:
import numpy as np

age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

a=np.where(height>155)
for i in a[0]:
    print(age[i], ' ', height[i])

15   156
19   180
20   162
21   157
22   158
23   179
16   182
18   183
20   159
15   160
17   172


In [300]:
import numpy as np
a=[[21, 20, 19, 18, 17], [16, 15, 14, 13, 12], [11, 10, 9, 8, 7], [6, 5, 4, 3, 2] ]
a=np.sort(a,axis=0)
print(a)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [311]:
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [320]:
import numpy as np 
dt = np.dtype('>i4') 
print(dt.name)

int32


In [356]:
#Total Killed in USA 

import csv
import numpy as np

file = open("terrorismData.csv", encoding="utf8")

data = csv.DictReader(file,skipinitialspace = True)

killed =[]
country =[]
for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    
np_killed = np.array(killed)
np_country = np.array(country)
np_killed[np_killed==''] = '0.0'
np_killed = np.array(np_killed,dtype=float)
bool_arr = np_country=='United States'
ans = np_killed[bool_arr]
ans1 = np.sum(ans)
print(int(ans1))

3771


In [2]:
#Terrorism Day

import numpy as np
import csv

day = []
with open("terrorismData.csv",encoding='utf8') as file_obj:
    file_data = csv.DictReader(file_obj, skipinitialspace = True)
    for row in file_data:
        day.append(row['Day'])
        
np_arr = np.array(day, dtype = 'float')
np_arr = np_arr[(np_arr >= 10) & (np_arr <= 20)]
print(np_arr.shape[0])

66330


In [11]:
import numpy as np
import csv

with open('terrorismData.csv') as file:
    data=csv.DictReader(file, skipinitialspace=True)
    day=[]
    count=[]
    for i in data:
        day.append(i['Day'])
        npday=np.array(day, dtype=int)
        day,count=np.unique(npday, return_count=True)
        print(day[np.argmax(count),count[np.argmax(count)]])

TypeError: _unique_dispatcher() got an unexpected keyword argument 'return_count'